# Generated by Django 5.0.7 on 2024-10-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='section',
            field=models.CharField(choices=[('S11', 'SECTION S11'), ('S12', 'SECTION S12'), ('S13', 'SECTION S13'), ('S14', 'SECTION S14'), ('S15', 'SECTION S15'), ('S21', 'SECTION S21'), ('S22', 'SECTION S22'), ('S23', 'SECTION S23'), ('S24', 'SECTION S24'), ('S25', 'SECTION S25')], max_length=50),
        ),
    ]
